background #0d0d0f
foreground #e5e9f0
selection_background #88c0d0
selection_foreground #0d0d0f
url_color #88c0d0
cursor #88c0d0
background_opacity 0.84
color0  #1a1a1e
color8  #3a3a3e
color1  #f28779
color9  #f28779
color2  #87c181
color10 #87c181
color3  #d9bc8c
color11 #d9bc8c
color4  #7bafd4
color12 #7bafd4
color5  #88c0d0
color13 #88c0d0
color6  #80c4c4
color14 #80c4c4
color7  #cecece
color15 #f5f5f5
