background #0d0d0f
foreground #e5e9f0
selection_background #88c0d0
selection_foreground #0d0d0f
url_color #88c0d0
cursor #88c0d0
background_opacity 0.92
color5  #88c0d0
color13 #88c0d0
color7  #e5e9f0
color15 #eceff4
