# ── Fonte ──────────────────────────────────────────────────────────────────
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        11.0

# ── Espaçamento ────────────────────────────────────────────────────────────
modify_font      cell_height 120%
letter_spacing   0.3

# ── Cursor ─────────────────────────────────────────────────────────────────
cursor_shape           beam
cursor_beam_thickness  1.5
cursor_blink_interval  0.5
cursor_stop_blinking_after 15.0

# ── Scroll ─────────────────────────────────────────────────────────────────
scrollback_lines 8000
wheel_scroll_multiplier 3.0

# ── Janela ─────────────────────────────────────────────────────────────────
window_padding_width    14 18
hide_window_decorations yes
confirm_os_window_close 0
remember_window_size    no
initial_window_width    900
initial_window_height   560

# ── Bell ─────────────────────────────────────────────────────────────────────
enable_audio_bell no
visual_bell_duration 0.0

# ── Misc ─────────────────────────────────────────────────────────────────────
strip_trailing_spaces smart
close_on_child_death  no
shell_integration     enabled
allow_remote_control yes
listen_on unix:/tmp/kitty-socket

include /home/ankh/dotfiles/generated/kitty/colors.conf
