general {
  disable_loading_bar = true
  hide_cursor         = true
}

background {
  monitor =
  path    = ~/.current-wallpaper
  blur_passes = 0
}

input-field {
  monitor =
  size = 280, 48
  outline_thickness = 1
  outer_color       = rgb(111113)
  inner_color       = rgb(0d0d0f)
  font_color        = rgb(e0e0e0)
  fade_on_empty     = false
  placeholder_text  = senha...
  check_color       = rgb(cf9fff)
  fail_color        = rgb(ff5555)
  fail_text         = incorreta
  rounding          = 8
  position          = 0, -80
  halign            = center
  valign            = center
}

label {
  monitor =
  text    = cmd[update:1000] date '+%H:%M'
  color   = rgb(e0e0e0)
  font_size = 48
  font_family = JetBrainsMono Nerd Font
  position  = 0, 80
  halign    = center
  valign    = center
}
