# Strata Habitus — Starship prompt
format = """$directory$git_branch$git_status$cmd_duration$line_break$character"""
add_newline = false
[directory]
style            = "bold #1a6a9a"
truncation_length = 3
truncate_to_repo  = true
read_only        = " 󰌾"
read_only_style  = "#f28779"
format           = "[$path]($style)[$read_only]($read_only_style) "
[git_branch]
style  = "#286e38"
format = "[ $branch]($style) "
[git_status]
style  = "#b4637a"
format = "([$all_status$ahead_behind]($style) )"
[cmd_duration]
style  = "dimmed #1a6a9a"
format = "[ ${duration}]($style) "
[character]
success_symbol = "[❯](bold #b4637a)"
error_symbol   = "[❯](bold red)"
