# Strata Habitus — Starship prompt
format = """$directory$git_branch$git_status$cmd_duration$line_break$character"""
add_newline = false
[directory]
style            = "bold #cf9fff"
truncation_length = 3
truncate_to_repo  = true
read_only        = " 󰌾"
read_only_style  = "#f28779"
format           = "[$path]($style)[$read_only]($read_only_style) "
[git_branch]
style  = "#87c181"
format = "[ $branch]($style) "
[git_status]
style  = "#d79921"
format = "([$all_status$ahead_behind]($style) )"
[cmd_duration]
style  = "dimmed #cf9fff"
format = "[ ${duration}]($style) "
[character]
success_symbol = "[❯](bold #d79921)"
error_symbol   = "[❯](bold red)"
