general {
  disable_loading_bar = true
  hide_cursor         = true
}

background {
  monitor =
  path    = ~/dotfiles/wallpaper.jpg
  blur_passes  = 2
  blur_size    = 6
  brightness   = 0.6
}

# horas
label {
  monitor =
  text    = cmd[update:1000] date '+%H'
  color   = rgba(e8ffffffe)
  font_size   = 140
  font_family = sans-serif
  position    = 0, 200
  halign      = center
  valign      = center
}

# minutos (cor de acento)
label {
  monitor =
  text    = cmd[update:1000] date '+%M'
  color   = rgba(8aad91d9)
  font_size   = 140
  font_family = sans-serif
  position    = 0, 50
  halign      = center
  valign      = center
}

# campo de senha
input-field {
  monitor =
  size    = 280, 44
  outline_thickness = 1
  outer_color       = rgba(ffffff25)
  inner_color       = rgba(ffffff15)
  font_color        = rgba(ffffffe0)
  fade_on_empty     = false
  placeholder_text  = Password
  check_color       = rgba(8aad91ff)
  fail_color        = rgba(ff6b6bff)
  fail_text         = Wrong password
  rounding          = 22
  position          = 0, -120
  halign            = center
  valign            = center
}
